use agent_core::{AgentCore, CoreProfile};

const STATIC_PROMPT: &str = include_str!("../../resources/static_v1.md");

fn main() {
    let mut memory_dir = std::env::temp_dir();
    memory_dir.push(format!("timem_static_prompt_expand_{}", std::process::id()));
    let core = AgentCore::new(
        STATIC_PROMPT,
        CoreProfile {
            name: "snapshot".to_string(),
            provider: "snapshot".to_string(),
            model: "snapshot".to_string(),
        },
        memory_dir,
    );

    println!("# Expanded Static Prompt Snapshot");
    println!();
    println!("Generated by `scripts/update_static_prompt_snapshot.sh`.");
    println!();
    println!(
        "This file is a read-only audit snapshot for humans. It is not read by Timem at runtime."
    );
    println!();
    println!("```text");
    println!("{}", core.render_prompt());
    println!("```");
}
