use agent_core::{AgentCore, CoreProfile, ResponseProtocolKind};

const STATIC_PROMPT: &str = include_str!("../../resources/system_prompt/system_prompt.md");

fn main() {
    let mut memory_dir = std::env::temp_dir();
    memory_dir.push(format!("timem_static_prompt_expand_{}", std::process::id()));
    let mut core = AgentCore::new(
        STATIC_PROMPT,
        CoreProfile {
            name: "snapshot".to_string(),
            provider: "snapshot".to_string(),
            model: "snapshot".to_string(),
        },
        memory_dir,
    );
    let response_protocol = std::env::var("TIMEM_RESPONSE_PROTOCOL")
        .ok()
        .map(|value| ResponseProtocolKind::from_name(&value))
        .unwrap_or(ResponseProtocolKind::Markdown);
    core.set_response_protocol(response_protocol);

    println!("# Expanded Static Prompt Snapshot");
    println!();
    println!("Generated by `scripts/update_static_prompt_snapshot.sh`.");
    println!("Response protocol: `{}`.", response_protocol.name());
    println!();
    println!(
        "This file is a read-only audit snapshot for humans. It is not read by Timem at runtime."
    );
    println!();
    println!("{}", core.render_prompt());
}
